const onBoardingData = {
	basicInfo: {
		name: 'Tom Holland',
		user_type: 'Private',
		industry_domain: 'Bakeries',
		business_description: 'We make yummy cookies',
		business_url: 'www.toomcooks.com',
		business_email_id: 'tomcooks@gmail.com',
	},
	bussinessInfo: {
		pan_number: 'AAAAA1234A',
		gstin_number: 'GST-123456789',
		currency_default: 'INR',
		currency_business: ['INR', 'USD'],
		address: '1/XYZ Lane21',
		city: 'Indore',
		state: 'MP',
		country: 'India',
		zip: '450001',
	},
	personalInfo: {
		pan_number: 'AAAAA1234A',
		name: 'sit amet',
		email: 'sitamet@gmail.com',
		contact: '+919999923456',
		pan_name: 'sit amet',
		position: 'Director',
		director: 'True',
		address_proof: 'Aadhar Card',
	},
	bankInfo: {
		beneficiary_name: 'Lorem ipsum',
		ifsc_code: 'XYZX12345',
		account_number: 123456789000,
	},
	authoriserInfo: {
		authorisers: [
			{
				name: 'Etiam dictum',
				director: 'True',
				shareholder: 'True',
				address: '123 lorem feugiat, laoreet',
				date_of_birth: '01-01-1989',
				shares_type: 'equity',
				percentage_holding: '25',
				shares_number: '50000',
				pan_card: 'PAN2L34JK44',
				aadhar_card: 7894561234,
			},
			{
				name: 'lOREM dictum',
				director: 'True',
				shareholder: 'False',
				address: '12/c volutpat quam, eget accumsan',
				date_of_birth: '01-01-1989',
				shares_type: '',
				percentage_holding: '',
				shares_number: '',
				pan_card: 'PAN123444444',
				aadhar_card: 1234567128,
			},
			{
				name: 'lOREM dictum',
				director: 'True',
				shareholder: 'False',
				address: '12/c volutpat quam, eget accumsan',
				date_of_birth: '01-01-1989',
				shares_type: '',
				percentage_holding: '',
				shares_number: '',
				pan_card: 'PAN123444444',
				aadhar_card: 1234567128,
			},
			{
				name: 'Etiam dictum',
				director: 'True',
				shareholder: 'True',
				address: '123 lorem feugiat, laoreet',
				date_of_birth: '01-01-1989',
				shares_type: 'equity',
				percentage_holding: '25',
				shares_number: '50000',
				pan_card: 'PAN2L34JK44',
				aadhar_card: 7894561234,
			},
			{
				name: 'lOREM dictum',
				director: 'True',
				shareholder: 'False',
				address: '12/c volutpat quam, eget accumsan',
				date_of_birth: '01-01-1989',
				shares_type: '',
				percentage_holding: '',
				shares_number: '',
				pan_card: 'PAN123444444',
				aadhar_card: 1234567128,
			},
			{
				name: 'lOREM dictum',
				director: 'True',
				shareholder: 'False',
				address: '12/c volutpat quam, eget accumsan',
				date_of_birth: '01-01-1989',
				shares_type: '',
				percentage_holding: '',
				shares_number: '',
				pan_card: 'PAN123444444',
				aadhar_card: 1234567128,
			},
		],
	},
	insalesInfo: {
		instarem: 'True',
		masspay: 'False',
		bizpay: 'True',
		receive: 'True',
		purpose_code: 'P12345',
		legal_name: 'Mauris dictum',
		incorporation_country: 'India',
		company_registration_number: 'L62815DL2019PLC988725',
		industry: 'Bakeries',
		name: 'viverra erat',
		number: '+917777754789',
		email: 'xyz@gmail.com',
		website: 'www.xyz.com',
		business_nature: 'Morbi pharetra libero augue',
		business_purpose: 'Proin aliquam lorem nec ',
		payment_received_country: 'India',
		advertisement_strategy:
			'Suspendisse feugiat porttitor risus,Suspendisse feugiat porttitor risus,Suspendisse feugiat porttitor risus',
		violations: 'False',
		average_transaction_value: '70000',
		expected_monthly_volumes: '1000000',
		approx_annual_turnover: '12000000',
	},
};

export default onBoardingData;
